module.exports = [
    { names: "Sweater" },
    { names: "Dress" },
    { names: "Hoodies" },
    { names: "Tshirt"},
    { names: "FlipFlops" },
    { names: "Shorts" },
    { names: "Skirt" },
    { names: "Jeans" },
    { names: "Shoes" },
    { names: "Coat" },
    { names: "HighHeels" },
    { names: "Suit" },
    { names: "Cap" },
    { names: "Socks" },
    { names: "Shirt" },
    { names: "Scarf" },
    { names: "Swimsuit" },
    { names: "Hat" },
    { names: "Gloves" },
    { names: "Jacket" },
    { names: "Longcoat" },
    { names: "Boots" },
    { names: "Sunglasses" },
    { names: "Tie" },
    { names: "Poloshirt" },
    { names: "LeatherJacket" }]